import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { OnlineStatusProvider } from "@/context/OnlineStatusContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <AntdRegistry>
          <OnlineStatusProvider>
            {children}
          </OnlineStatusProvider>
        </AntdRegistry>
        <Toaster />
      </body>
    </html>
  );
}
